"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _PressureChannel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PressureChannelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PressureChannel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CHANNEL_1: _PressureChannel.ValueType  # 0
    CHANNEL_2: _PressureChannel.ValueType  # 1
    CHANNEL_3: _PressureChannel.ValueType  # 2
    CHANNEL_4: _PressureChannel.ValueType  # 3

class PressureChannel(_PressureChannel, metaclass=_PressureChannelEnumTypeWrapper): ...

CHANNEL_1: PressureChannel.ValueType  # 0
CHANNEL_2: PressureChannel.ValueType  # 1
CHANNEL_3: PressureChannel.ValueType  # 2
CHANNEL_4: PressureChannel.ValueType  # 3
global___PressureChannel = PressureChannel
