# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argus/pressure/pressure_reading.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'argus/pressure/pressure_reading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages.argus import adc_pb2 as argus_dot_adc__pb2
from messages.argus.pressure import pressure_channel_pb2 as argus_dot_pressure_dot_pressure__channel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%argus/pressure/pressure_reading.proto\x12(messages.argus.pressure.pressure_reading\x1a\x0f\x61rgus/adc.proto\x1a%argus/pressure/pressure_channel.proto\"\x94\x02\n\x0fPressureReading\x12\x1a\n\rlocal_session\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x31\n\nadc_device\x18\x02 \x01(\x0e\x32\x1d.messages.argus.adc.AdcDevice\x12S\n\x10pressure_channel\x18\x03 \x01(\x0e\x32\x39.messages.argus.pressure.pressure_channel.PressureChannel\x12\x13\n\x0brecorded_at\x18\x04 \x01(\x04\x12\x0f\n\x07voltage\x18\x05 \x01(\x02\x12\x10\n\x08pressure\x18\x08 \x01(\x02\x12\x13\n\x0btemperature\x18\x06 \x01(\x01\x42\x10\n\x0e_local_sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argus.pressure.pressure_reading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESSUREREADING']._serialized_start=140
  _globals['_PRESSUREREADING']._serialized_end=416
# @@protoc_insertion_point(module_scope)
