{
 "title": "Thermocouple Readings",
 "tags": [
  "argus",
  "temperature"
 ],
 "time": { "from": "1969-12-31T23:27:09.905Z", "to": "1970-01-01T02:36:30.513Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "session_number", "label": "Session Number" },
   { "name": "thermocouple_channel", "label": "Thermocouple Channel", "query": "0,1,2,3" }
  ]
 },
 "panels": [
  {
   "title": "ADC 0 Channel ${thermocouple_channel}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "repeat": "thermocouple_channel",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"compensated_temperature\" AS \"Compensated Temperature\",\n  \"cold_junction_temperature\" AS \"Cold Junction Temperature\",\n  \"timestamp\" AS \"time\" \nFROM thermocouple_readings \nWHERE \n  session_id = $session_number \n  AND adc_device = '0'\n  AND thermocouple_channel = $thermocouple_channel \nORDER BY timestamp\nDESC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "ADC 1 Channel ${thermocouple_channel}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 8, "y": 0 },
   "repeat": "thermocouple_channel",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"compensated_temperature\" AS \"Compensated Temperature\",\n  \"cold_junction_temperature\" AS \"Cold Junction Temperature\",\n  \"timestamp\" AS \"time\" \nFROM thermocouple_readings \nWHERE \n  session_id = $session_number \n  AND adc_device = '1'\n  AND thermocouple_channel = $thermocouple_channel \nORDER BY timestamp\nDESC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Latest Session Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT MAX(session_id) FROM thermocouple_readings LIMIT 50 "
    }
   ]
  }
 ]
}