# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argus/temperature/thermocouple_reading.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'argus/temperature/thermocouple_reading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages.argus import adc_pb2 as argus_dot_adc__pb2
from messages.argus.temperature import thermocouple_channel_pb2 as argus_dot_temperature_dot_thermocouple__channel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,argus/temperature/thermocouple_reading.proto\x12/messages.argus.temperature.thermocouple_reading\x1a\x0f\x61rgus/adc.proto\x1a,argus/temperature/thermocouple_channel.proto\"\xe7\x02\n\x13ThermocoupleReading\x12\x1a\n\rlocal_session\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x31\n\nadc_device\x18\x02 \x01(\x0e\x32\x1d.messages.argus.adc.AdcDevice\x12\x62\n\x14thermocouple_channel\x18\x03 \x01(\x0e\x32\x44.messages.argus.temperature.thermocouple_channel.ThermocoupleChannel\x12\x13\n\x0brecorded_at\x18\x04 \x01(\x04\x12\x0f\n\x07voltage\x18\x05 \x01(\x02\x12\x1f\n\x17\x63ompensated_temperature\x18\x06 \x01(\x01\x12!\n\x19uncompensated_temperature\x18\x07 \x01(\x01\x12!\n\x19\x63old_junction_temperature\x18\x08 \x01(\x02\x42\x10\n\x0e_local_sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argus.temperature.thermocouple_reading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THERMOCOUPLEREADING']._serialized_start=161
  _globals['_THERMOCOUPLEREADING']._serialized_end=520
# @@protoc_insertion_point(module_scope)
