"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ThermocoupleChannel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ThermocoupleChannelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ThermocoupleChannel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CHANNEL_1: _ThermocoupleChannel.ValueType  # 0
    CHANNEL_2: _ThermocoupleChannel.ValueType  # 1
    CHANNEL_3: _ThermocoupleChannel.ValueType  # 2
    CHANNEL_4: _ThermocoupleChannel.ValueType  # 3

class ThermocoupleChannel(_ThermocoupleChannel, metaclass=_ThermocoupleChannelEnumTypeWrapper): ...

CHANNEL_1: ThermocoupleChannel.ValueType  # 0
CHANNEL_2: ThermocoupleChannel.ValueType  # 1
CHANNEL_3: ThermocoupleChannel.ValueType  # 2
CHANNEL_4: ThermocoupleChannel.ValueType  # 3
global___ThermocoupleChannel = ThermocoupleChannel
