# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argus/temperature/thermocouple_calibration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'argus/temperature/thermocouple_calibration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages.argus import adc_pb2 as argus_dot_adc__pb2
from messages.argus.temperature import thermocouple_channel_pb2 as argus_dot_temperature_dot_thermocouple__channel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0argus/temperature/thermocouple_calibration.proto\x12\x33messages.argus.temperature.thermocouple_calibration\x1a\x0f\x61rgus/adc.proto\x1a,argus/temperature/thermocouple_channel.proto\"\x98\t\n\x17ThermocoupleCalibration\x12\x8d\x01\n\x1bselect_thermocouple_request\x18\x01 \x01(\x0b\x32\x66.messages.argus.temperature.thermocouple_calibration.ThermocoupleCalibration.SelectThermocoupleRequestH\x00\x12\x8a\x01\n\x1a\x63ollect_data_point_request\x18\x02 \x01(\x0b\x32\x64.messages.argus.temperature.thermocouple_calibration.ThermocoupleCalibration.CollectDataPointRequestH\x00\x12\x8c\x01\n\x1b\x63ollect_data_point_response\x18\x03 \x01(\x0b\x32\x65.messages.argus.temperature.thermocouple_calibration.ThermocoupleCalibration.CollectDataPointResponseH\x00\x12\x8b\x01\n\x1aperform_regression_request\x18\x04 \x01(\x0b\x32\x65.messages.argus.temperature.thermocouple_calibration.ThermocoupleCalibration.PerformRegressionRequestH\x00\x12\x8d\x01\n\x1b\x63\x61libration_result_response\x18\x05 \x01(\x0b\x32\x66.messages.argus.temperature.thermocouple_calibration.ThermocoupleCalibration.CalibrationResultResponseH\x00\x1a\xb2\x01\n\x19SelectThermocoupleRequest\x12\x31\n\nadc_device\x18\x01 \x01(\x0e\x32\x1d.messages.argus.adc.AdcDevice\x12\x62\n\x14thermocouple_channel\x18\x02 \x01(\x0e\x32\x44.messages.argus.temperature.thermocouple_channel.ThermocoupleChannel\x1a+\n\x17\x43ollectDataPointRequest\x12\x10\n\x08\x65xpected\x18\x01 \x01(\x01\x1a>\n\x18\x43ollectDataPointResponse\x12\x10\n\x08measured\x18\x01 \x01(\x01\x12\x10\n\x08\x65xpected\x18\x02 \x01(\x01\x1a\x1a\n\x18PerformRegressionRequest\x1aj\n\x19\x43\x61librationResultResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\x05scale\x18\x02 \x01(\x01H\x00\x88\x01\x01\x12\x13\n\x06offset\x18\x03 \x01(\x01H\x01\x88\x01\x01\x42\x08\n\x06_scaleB\t\n\x07_offsetB\t\n\x07messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argus.temperature.thermocouple_calibration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THERMOCOUPLECALIBRATION']._serialized_start=169
  _globals['_THERMOCOUPLECALIBRATION']._serialized_end=1345
  _globals['_THERMOCOUPLECALIBRATION_SELECTTHERMOCOUPLEREQUEST']._serialized_start=911
  _globals['_THERMOCOUPLECALIBRATION_SELECTTHERMOCOUPLEREQUEST']._serialized_end=1089
  _globals['_THERMOCOUPLECALIBRATION_COLLECTDATAPOINTREQUEST']._serialized_start=1091
  _globals['_THERMOCOUPLECALIBRATION_COLLECTDATAPOINTREQUEST']._serialized_end=1134
  _globals['_THERMOCOUPLECALIBRATION_COLLECTDATAPOINTRESPONSE']._serialized_start=1136
  _globals['_THERMOCOUPLECALIBRATION_COLLECTDATAPOINTRESPONSE']._serialized_end=1198
  _globals['_THERMOCOUPLECALIBRATION_PERFORMREGRESSIONREQUEST']._serialized_start=1200
  _globals['_THERMOCOUPLECALIBRATION_PERFORMREGRESSIONREQUEST']._serialized_end=1226
  _globals['_THERMOCOUPLECALIBRATION_CALIBRATIONRESULTRESPONSE']._serialized_start=1228
  _globals['_THERMOCOUPLECALIBRATION_CALIBRATIONRESULTRESPONSE']._serialized_end=1334
# @@protoc_insertion_point(module_scope)
