[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

# -----------------------
# Host Testing
# -----------------------

[tasks.test-host]
dependencies = ["test-thermocouple-converter"]

# -----------------------
# Embedded Testing
# -----------------------

[tasks.test-embedded]
dependencies = [
    "test-argus-temperature",
    "test-argus-pressure",
    "test-argus-strain",
]

[tasks.test-argus-temperature]
command = "cargo"
args = ["test", "-p", "argus", "--features", "temperature", "${@}"]

[tasks.test-argus-pressure]
command = "cargo"
args = ["test", "-p", "argus", "--features", "pressure", "${@}"]

[tasks.test-argus-strain]
command = "cargo"
args = ["test", "-p", "argus", "--features", "strain", "${@}"]

[tasks.test-thermocouple-converter]
command = "cargo"
args = [
    "test",
    "-p",
    "thermocouple-converter",
    "--target",
    "${CARGO_MAKE_RUST_TARGET_TRIPLE}",
]
env = { RUST_MIN_STACK = "8388608" }
