[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

# -----------------------
# Host Testing
# -----------------------

[tasks.test-host]
dependencies = []
# -----------------------
# Embedded Testing
# -----------------------

[tasks.test-embedded]
dependencies = [
    "test-argus-temperature",
    "test-argus-pressure",
    "test-argus-strain",
]

[tasks.test-argus-temperature]
command = "cargo"
args = ["test", "-p", "argus", "--features", "temperature", "${@}"]

[tasks.test-argus-pressure]
command = "cargo"
args = ["test", "-p", "argus", "--features", "pressure", "${@}"]

[tasks.test-argus-strain]
command = "cargo"
args = ["test", "-p", "argus", "--features", "strain", "${@}"]
