"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _AdcDevice:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AdcDeviceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AdcDevice.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADC_DEVICE_1: _AdcDevice.ValueType  # 0
    ADC_DEVICE_2: _AdcDevice.ValueType  # 1

class AdcDevice(_AdcDevice, metaclass=_AdcDeviceEnumTypeWrapper): ...

ADC_DEVICE_1: AdcDevice.ValueType  # 0
ADC_DEVICE_2: AdcDevice.ValueType  # 1
global___AdcDevice = AdcDevice
