# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argus/envelope.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'argus/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from argus.temperature import thermocouple_calibration_request_pb2 as argus_dot_temperature_dot_thermocouple__calibration__request__pb2
from argus.temperature import thermocouple_reading_pb2 as argus_dot_temperature_dot_thermocouple__reading__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61rgus/envelope.proto\x12\x17messages.argus.envelope\x1a\x38\x61rgus/temperature/thermocouple_calibration_request.proto\x1a,argus/temperature/thermocouple_reading.proto\"\x85\x02\n\x08\x45nvelope\x12\x87\x01\n thermocouple_calibration_request\x18\x01 \x01(\x0b\x32[.messages.argus.temperature.thermocouple_calibration_request.ThermocoupleCalibrationRequestH\x00\x12\x64\n\x14thermocouple_reading\x18\x02 \x01(\x0b\x32\x44.messages.argus.temperature.thermocouple_reading.ThermocoupleReadingH\x00\x42\t\n\x07messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argus.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVELOPE']._serialized_start=154
  _globals['_ENVELOPE']._serialized_end=415
# @@protoc_insertion_point(module_scope)
