"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import argus.temperature.thermocouple_calibration_pb2
import argus.temperature.thermocouple_reading_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Envelope(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    THERMOCOUPLE_CALIBRATION_FIELD_NUMBER: builtins.int
    THERMOCOUPLE_READING_FIELD_NUMBER: builtins.int
    @property
    def thermocouple_calibration(self) -> argus.temperature.thermocouple_calibration_pb2.ThermocoupleCalibration: ...
    @property
    def thermocouple_reading(self) -> argus.temperature.thermocouple_reading_pb2.ThermocoupleReading: ...
    def __init__(
        self,
        *,
        thermocouple_calibration: argus.temperature.thermocouple_calibration_pb2.ThermocoupleCalibration | None = ...,
        thermocouple_reading: argus.temperature.thermocouple_reading_pb2.ThermocoupleReading | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "thermocouple_calibration", b"thermocouple_calibration", "thermocouple_reading", b"thermocouple_reading"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "thermocouple_calibration", b"thermocouple_calibration", "thermocouple_reading", b"thermocouple_reading"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["message", b"message"]) -> typing.Literal["thermocouple_calibration", "thermocouple_reading"] | None: ...

global___Envelope = Envelope
