# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argus/temperature.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'argus/temperature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from argus import adc_pb2 as argus_dot_adc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61rgus/temperature.proto\x12 messages_prost.argus.temperature\x1a\x0f\x61rgus/adc.proto\"\x9f\x01\n\x1eThermocoupleCalibrationRequest\x12\x44\n\x0cthermocouple\x18\x01 \x01(\x0e\x32..messages_prost.argus.temperature.Thermocouple\x12\x37\n\nadc_device\x18\x02 \x01(\x0e\x32#.messages_prost.argus.adc.AdcDevice*^\n\x0cThermocouple\x12\x12\n\x0eTHERMOCOUPLE_1\x10\x00\x12\x12\n\x0eTHERMOCOUPLE_2\x10\x01\x12\x12\n\x0eTHERMOCOUPLE_3\x10\x02\x12\x12\n\x0eTHERMOCOUPLE_4\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argus.temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THERMOCOUPLE']._serialized_start=240
  _globals['_THERMOCOUPLE']._serialized_end=334
  _globals['_THERMOCOUPLECALIBRATIONREQUEST']._serialized_start=79
  _globals['_THERMOCOUPLECALIBRATIONREQUEST']._serialized_end=238
# @@protoc_insertion_point(module_scope)
