# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argus/temperature/thermocouple_channel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'argus/temperature/thermocouple_channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,argus/temperature/thermocouple_channel.proto\x12/messages.argus.temperature.thermocouple_channel*Q\n\x13ThermocoupleChannel\x12\r\n\tCHANNEL_1\x10\x00\x12\r\n\tCHANNEL_2\x10\x01\x12\r\n\tCHANNEL_3\x10\x02\x12\r\n\tCHANNEL_4\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argus.temperature.thermocouple_channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THERMOCOUPLECHANNEL']._serialized_start=97
  _globals['_THERMOCOUPLECHANNEL']._serialized_end=178
# @@protoc_insertion_point(module_scope)
