{
 "title": "Pressure Readings",
 "tags": [
  "argus",
  "pressure"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host_session_id", "label": "Host Session Id" },
   { "name": "pressure_channel", "label": "Pressure Channel", "query": "0,1,2,3" }
  ]
 },
 "panels": [
  {
   "title": "ADC 0 Channel ${pressure_channel}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "repeat": "pressure_channel",
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"pressure\" AS \"Pressure\",\n  \"stored_at\" AS \"time\" \nFROM pressure_readings \nWHERE \n  host_session_id = $host_session_id\n  AND adc_device = '0'\n  AND pressure_channel = $pressure_channel \nORDER BY stored_at DESC"
    }
   ]
  },
  {
   "title": "ADC 1 Channel ${pressure_channel}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "repeat": "pressure_channel",
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"pressure\" AS \"Pressure\",\n  \"stored_at\" AS \"time\" \nFROM pressure_readings \nWHERE \n  host_session_id = $host_session_id \n  AND adc_device = '1'\n  AND pressure_channel = $pressure_channel \nORDER BY stored_at DESC"
    }
   ]
  },
  {
   "title": "Latest Session Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT\n  MAX(host_session_id)\nFROM\n  pressure_readings \nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Voltage: ADC 0 Channel ${pressure_channel}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "repeat": "pressure_channel",
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"voltage\" AS \"Voltage\",\n  \"stored_at\" AS \"time\" \nFROM pressure_readings \nWHERE \n  host_session_id = $host_session_id \n  AND adc_device = '0'\n  AND pressure_channel = $pressure_channel \nORDER BY stored_at DESC"
    }
   ]
  },
  {
   "title": "Voltage: ADC 1 Channel ${pressure_channel}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 32 },
   "repeat": "pressure_channel",
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"voltage\" AS \"Voltage\",\n  \"stored_at\" AS \"time\" \nFROM pressure_readings \nWHERE \n  host_session_id = $host_session_id \n  AND adc_device = '1'\n  AND pressure_channel = $pressure_channel \nORDER BY stored_at DESC"
    }
   ]
  }
 ]
}