{
 "title": "Thermocouple Readings",
 "tags": [
  "argus",
  "temperature"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "host_session_id", "label": "Host Session Id" },
   { "name": "thermocouple_channel", "label": "Thermocouple Channel", "query": "0,1,2,3" }
  ]
 },
 "panels": [
  {
   "title": "ADC 0 Channel ${thermocouple_channel}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "repeat": "thermocouple_channel",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"compensated_temperature\" AS \"Compensated Temperature\",\n  \"cold_junction_temperature\" AS \"Cold Junction Temperature\",\n  \"stored_at\" AS \"time\" \nFROM thermocouple_readings \nWHERE \n  host_session_id = $host_session_id\n  AND adc_device = '0'\n  AND thermocouple_channel = $thermocouple_channel \nORDER BY stored_at DESC"
    }
   ]
  },
  {
   "title": "ADC 1 Channel ${thermocouple_channel}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 0 },
   "repeat": "thermocouple_channel",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"compensated_temperature\" AS \"Compensated Temperature\",\n  \"cold_junction_temperature\" AS \"Cold Junction Temperature\",\n  \"stored_at\" AS \"time\" \nFROM thermocouple_readings \nWHERE \n  host_session_id = $host_session_id \n  AND adc_device = '1'\n  AND thermocouple_channel = $thermocouple_channel \nORDER BY stored_at DESC"
    }
   ]
  },
  {
   "title": "Latest Session Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT MAX(host_session_id) FROM thermocouple_readings LIMIT 50 "
    }
   ]
  },
  {
   "title": "Voltage: ADC 0 Channel ${thermocouple_channel}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 44 },
   "repeat": "thermocouple_channel",
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"voltage\" AS \"Voltage\",\n  \"stored_at\" AS \"time\" \nFROM thermocouple_readings \nWHERE \n  host_session_id = $host_session_id \n  AND adc_device = '0'\n  AND thermocouple_channel = $thermocouple_channel \nORDER BY stored_at DESC"
    }
   ]
  },
  {
   "title": "Voltage: ADC 1 Channel ${thermocouple_channel}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 44 },
   "repeat": "thermocouple_channel",
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "dataset": "uorocketry",
     "rawSql": "SELECT \n  \"voltage\" AS \"Voltage\",\n  \"stored_at\" AS \"time\" \nFROM thermocouple_readings \nWHERE \n  host_session_id = $host_session_id \n  AND adc_device = '1'\n  AND thermocouple_channel = $thermocouple_channel \nORDER BY stored_at DESC"
    }
   ]
  }
 ]
}