[tasks.rust-types]
description = "Build protobuf messages for Rust"
command = "cargo"
args = ["build"]

[tasks.python-types]
description = "Build protobuf messages for Python"
script_runner = "@shell"
script = [
	"rm -rf python/messages",
	"mkdir python/messages",
	"""python3 -m grpc_tools.protoc \
		--proto_path=proto \
		--python_out=python/messages \
		--mypy_out=python/messages \
		--grpc_python_out=python/messages \
	$(find proto -type f -name '*.proto')""",
	"find python/messages -type d -exec touch {}/__init__.py \\;",
	"./utils/prefix-python-imports.sh python/messages messages",
]

[tasks.all]
description = "Build all protobuf messages"
dependencies = ["rust-types", "python-types"]
