"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import messages.argus.adc_pb2
import messages.argus.strain.strain_channel_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StrainReading(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOCAL_SESSION_FIELD_NUMBER: builtins.int
    ADC_DEVICE_FIELD_NUMBER: builtins.int
    STRAIN_CHANNEL_FIELD_NUMBER: builtins.int
    RECORDED_AT_FIELD_NUMBER: builtins.int
    VOLTAGE_FIELD_NUMBER: builtins.int
    STRAIN_FIELD_NUMBER: builtins.int
    local_session: builtins.int
    """Local session from the device that took the reading"""
    adc_device: argus.adc_pb2.AdcDevice.ValueType
    """ADC device from which the reading was taken"""
    strain_channel: argus.strain.strain_channel_pb2.StrainChannel.ValueType
    """Identifier for the strain gauge within the ADC device"""
    recorded_at: builtins.int
    """Milliseconds since the board's epoch when the reading was recorded"""
    voltage: builtins.float
    """Voltage difference measured at the strain wheatstone bridge in millivolts"""
    strain: builtins.float
    """Strain reading in microstrain"""
    def __init__(
        self,
        *,
        local_session: builtins.int | None = ...,
        adc_device: argus.adc_pb2.AdcDevice.ValueType = ...,
        strain_channel: argus.strain.strain_channel_pb2.StrainChannel.ValueType = ...,
        recorded_at: builtins.int = ...,
        voltage: builtins.float = ...,
        strain: builtins.float = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_local_session", b"_local_session", "local_session", b"local_session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_local_session", b"_local_session", "adc_device", b"adc_device", "local_session", b"local_session", "recorded_at", b"recorded_at", "strain", b"strain", "strain_channel", b"strain_channel", "voltage", b"voltage"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_local_session", b"_local_session"]) -> typing.Literal["local_session"] | None: ...

global___StrainReading = StrainReading
