# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: argus/strain/strain_reading.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'argus/strain/strain_reading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from messages.argus import adc_pb2 as argus_dot_adc__pb2
from messages.argus.strain import strain_channel_pb2 as argus_dot_strain_dot_strain__channel__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!argus/strain/strain_reading.proto\x12$messages.argus.strain.strain_reading\x1a\x0f\x61rgus/adc.proto\x1a!argus/strain/strain_channel.proto\"\xf3\x01\n\rStrainReading\x12\x1a\n\rlocal_session\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x31\n\nadc_device\x18\x02 \x01(\x0e\x32\x1d.messages.argus.adc.AdcDevice\x12K\n\x0estrain_channel\x18\x03 \x01(\x0e\x32\x33.messages.argus.strain.strain_channel.StrainChannel\x12\x13\n\x0brecorded_at\x18\x04 \x01(\x04\x12\x0f\n\x07voltage\x18\x05 \x01(\x02\x12\x0e\n\x06strain\x18\x08 \x01(\x01\x42\x10\n\x0e_local_sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'argus.strain.strain_reading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRAINREADING']._serialized_start=128
  _globals['_STRAINREADING']._serialized_end=371
# @@protoc_insertion_point(module_scope)
