name: uorocketry
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uorocketry
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
