"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _StrainChannel:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StrainChannelEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StrainChannel.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CHANNEL_1: _StrainChannel.ValueType  # 0
    CHANNEL_2: _StrainChannel.ValueType  # 1
    CHANNEL_3: _StrainChannel.ValueType  # 2
    CHANNEL_4: _StrainChannel.ValueType  # 3

class StrainChannel(_StrainChannel, metaclass=_StrainChannelEnumTypeWrapper): ...

CHANNEL_1: StrainChannel.ValueType  # 0
CHANNEL_2: StrainChannel.ValueType  # 1
CHANNEL_3: StrainChannel.ValueType  # 2
CHANNEL_4: StrainChannel.ValueType  # 3
global___StrainChannel = StrainChannel
