# A lot of these actions could have been a bash command but we're using predefined actions
# to take advantage of caching and other features they provide. It runs faster with the vendor actions.
name: Setup Rust Environment
description: Install deps, ARM toolchain, and Rust toolchain

runs:
  using: composite
  steps:
    - name: Rust build cache (crates + target)
      uses: Swatinem/rust-cache@v2
      with:
        # Cache is scoped by OS, Rust version, target triple, and workspace hash
        save-if: true
        cache-all-crates: true
        workspaces: |
          . -> target

    - name: Cache Rustup Toolchains
      uses: actions/cache@v3
      with:
        path: |
          ~/.rustup/toolchains/
          ~/.rustup/update-hashes/
        key: ${{ runner.os }}-rustup-stable-thumbv7em-none-eabihf

    - name: Disable man-db (skip Manual Page Installs)
      shell: bash
      run: |
        echo 'path-exclude /usr/share/man/*' | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc
        echo 'path-exclude /usr/share/doc/*' | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
        echo 'path-exclude /usr/share/doc-base/*' | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc

    - name: Install APT Dependencies
      shell: bash
      run: |
        sudo apt update
        sudo apt-get install -y --no-install-recommends cmake protobuf-compiler

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: "12.2.Rel1"

    - name: Install Rust Toolchain for Embedded Development
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv7em-none-eabihf
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Install Cargo Binaries (idempotent)
      shell: bash
      run: |
        set -euo pipefail
        ensure_bin() {
          local bin="$1"; shift
          if ! command -v "$bin" >/dev/null 2>&1; then
            echo "Installing $bin..."
            cargo install "$@"
          else
            echo "$bin already installed; skipping"
          fi
        }
        # Pin versions for reproducibility and better cache hits
        ensure_bin cargo-make cargo-make@0.37.7
        ensure_bin cargo-sort cargo-sort@1.0.9
