[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32H733VGTx --protocol swd"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[env]
DEFMT_LOG = "debug,embedded_sdmmc=info"

[build]
target = "thumbv7em-none-eabihf"

[alias]
attach = "probe-rs --chip STM32H733VGTx attach --connect-under-reset"